context:
  name: feedrattler
  version: "0.3.6"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/hadim/feedrattler/archive/refs/tags/${{ version }}.zip
  sha256: 81fb2e34e2e1812a24c83c315a5beb13c4c0cf7acdbdad96ab491ce613b3e93d

build:
  number: 1
  noarch: python
  script:
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
    content: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - feedrattler = feedrattler.cli:app

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
  run:
    - python >=${{ python_min }}
    - pygithub >=2.5
    - conda-smithy >=3.45
    - ruamel.yaml >=0.18
    - gitpython >=3.1
    - conda-recipe-manager >=0.4.0
    - typer >=0.15
    - rich >=13.9
    - python-dotenv >=1.0
    - gh >=2.67.0

tests:
  - python:
      imports:
        - feedrattler
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - ${{ "feedrattler --help" if unix }}
      - ${{ "feedrattler.exe --help" if win }}

about:
  summary: Convert conda-forge feedstock to rattler-build
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/hadim/feedrattler

extra:
  recipe-maintainers:
    - hadim
